name: py3139
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.9
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - kagglehub
  - optuna
  - xgboost